In [1]:
import numpy as np

In [4]:
arr1 = np.arange(0,11) # 0 to 10
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr1[8]

8

In [6]:
arr1[1:5]

array([1, 2, 3, 4])

In [7]:
arr1[0:5] = 100

In [9]:
arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr1 = arr1[0:6]
slice_of_arr1 

array([100, 100, 100, 100, 100,   5])

In [12]:
slice_of_arr1[:] = 100

In [13]:
slice_of_arr1

array([100, 100, 100, 100, 100, 100])

In [14]:
arr1

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [17]:
arr1_copy = arr1.copy()
arr1_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [21]:
arr_2d = np.array(([5,10,15],[3,4,5],[4,5,6]))
arr_2d

array([[ 5, 10, 15],
       [ 3,  4,  5],
       [ 4,  5,  6]])

In [23]:
arr_2d[0,0] # selcting 0,0

5

In [24]:
arr_2d[1,0]

3

In [25]:
arr_2d[:2,1:]

array([[10, 15],
       [ 4,  5]])

In [27]:
arr_2d[2]

array([4, 5, 6])

In [28]:
# fancy index
arr2d = np.zeros((10, 10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
# lengt
arr2d_leght = arr2d.shape[1]

In [32]:
arr2d_leght

10